version: '3'

services:
  facets-api:
    image: ghcr.io/openfoodfacts/facets-knowledge-panels:${TAG:-dev}
    ports:
      - "${API_EXPOSE}:80"
    volumes:
      - ./html:/code/html
    environment:
      FACETS_HUNGER_GAME:
      FACETS_OPENFOODFACTS:
      FACETS_WIKIDATA:
      FACETS_TAXONOMY:
      FACETS_INAO:
      FACETS_OPENSTREETMAP:
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "80"
      ]
    healthcheck:
      # very simple health check
      test:
        [
          "CMD-SHELL",
          "curl --silent --fail localhost:80/ >/dev/null || exit 1"
        ]
      interval: 10s
      timeout: 10s
      retries: 3
